# Generated by Django 5.2.1 on 2025-08-18 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_weights', models.BinaryField(blank=True, null=True)),
                ('reward_model_weights', models.BinaryField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.JSONField()),
                ('actions', models.JSONField()),
                ('rewards', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_preferred', models.BooleanField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project5.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='HumanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project5.trainingsession')),
                ('preferred_trajectory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project5.trajectory')),
                ('trajectory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback1', to='project5.trajectory')),
                ('trajectory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback2', to='project5.trajectory')),
            ],
        ),
    ]
